### PR TITLE
added 3 imp programs in cp

### PR DESCRIPTION
**Pull request by diva-21**
Hello there,i am an active Open Source contributor.
I saw your repo which was catchy, so wanted to contribute my work to you.
I have added 3 important programs as per interviews, they are Morris Traversal,N queens 2 (code in cp manner) and a DSU question
Kindly review it

### CODE REVIEW

**Comment by diva-21** [comment]
And also added Sudoku Solver which is a Backtracking question, fully commented and self explanatory

**Comment by IumoInfinium** [comment]
Hii @diva-21 
Happy to see that you are doing soo much but this repository is just a collection of my own solutions.
Thank you

**Comment by diva-21** [comment]
can you once merge one pr, i need it

**Comment by diva-21** [comment]
Later you can change according to your wish, but waiting for my pr to be merged

**Pull request closed without merging**
